### PR TITLE
Mp3 wav through mp3spi

### PR DESCRIPTION
**Pull request by fluddokt**
May have fixed loading some other unique audio.

### CODE REVIEW

**Comment by itdelatrisu** [comment]
What exactly does this fix?

**Comment by fluddokt** [comment]
Oh it fixes some audio that couldn't be loaded by some skins.

**Comment by itdelatrisu** [comment]
Do you have any examples?  (I believe you, but I'd just like to see for myself before adding more dependencies.)

**Comment by fluddokt** [comment]
Here some examples [from the Completed Skins Forum](http://osu.ppy.sh/forum/109)
[The Furry Skin!](http://osu.ppy.sh/forum/t/221594)
Failed to load file 'readys.wav'.
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
Failed to load file 'spinnerbonus.wav'.
java.lang.IllegalArgumentException: No line matching interface Clip supporting format PCM_SIGNED 44100.0 Hz, 24 bit, stereo, 6 bytes/frame, little-endian is supported.
etc....
[Minimalist](http://osu.ppy.sh/forum/t/197917)
[Metal Gear Osu!](http://osu.ppy.sh/forum/t/194169)
Failed to load file 'failsound.wav'.
java.lang.IllegalArgumentException: No line matching interface Clip supporting format PCM_FLOAT 96000.0 Hz, 32 bit, stereo, 8 bytes/frame,  is supported.
Failed to load file 'menuback.wav'.
java.lang.IllegalArgumentException: No line matching interface Clip supporting format PCM_SIGNED 96000.0 Hz, 24 bit, stereo, 6 bytes/frame, little-endian is supported.
Failed to load file 'normal-hitfinish.wav'.
java.lang.IllegalArgumentException: No line matching interface Clip supporting format PCM_SIGNED 44100.0 Hz, 24 bit, stereo, 6 bytes/frame, little-endian is supported.
Failed to load file 'drum-sliderslide.wav'.
java.io.EOFException
etc...
[Nexus Slate](http://osu.ppy.sh/forum/t/55948)
Failed to load file 'menuback.wav'.
javax.sound.sampled.UnsupportedAudioFileException: could not get audio input stream from input URL
[Luminance](http://osu.ppy.sh/forum/t/168372)

**Comment by itdelatrisu** [comment]
Great, thanks!

**Pull request merged**
