### PR TITLE
Pulse main menu logo to the beat, add pulsing logo in song menu

### LINKED ISSUE #163: [Feature Request] Bumping Effects on opsu! logo

### PR DESCRIPTION
**Pull request by yugecin**
close #163 when merged
I made it pulse at 1Hz when music is paused, which may look a bit weird with the scaling. Adjust if needed.

### CODE REVIEW

**Comment by Lemmmy** [comment]
1Hz should be fine IMO - the menu pulses at 60bpm (1Hz) wehn nothing is playing in osu! too.

**Comment by itdelatrisu** [comment]
Looks great!  Good job with the logic to get the beats -- I'd never thought about doing it this way.

Some comments:

* The `parseOnlyTimingPoints()` method doesn't need `MD5InputStreamWrapper` since it's not computing the file's MD5 hash.
* In the song menu in osu!, you can click the logo to start the game (call `startGame()`).  Also, hovering over the logo makes it stop pulsing and scales it to ~140% (can't tell exactly).

**Comment by yugecin** [comment]
Thanks :)
I removed the MD5 wrapper and made the logo a button. When the logo is expanded, the non-expanded hitbox is still used like in osu!. The scale was indeed 140%

**Comment by itdelatrisu** [comment]
Thanks! :)

**Pull request merged**
