### PR TITLE
Make extracted ffmpeg executable

### PR DESCRIPTION
**Pull request by jrb0001**
This also makes `./gradlew` executable for easier building on linux.

### CODE REVIEW

**Comment by itdelatrisu** [comment]
Can you explain / can anyone else confirm?  No one has reported this to be an issue and the feature has been out for a long time now.

**Comment by jrb0001** [comment]
Opsu failed to play background videos and the log showed stacktraces caused by the ffmpeg file not being executable.

**Comment by tpenguinltg** [comment]
Confirmed. I probably haven't noticed because I build using the system FFmpeg and turn videos off.

However, this patch isn't enough to fix the problem. The patch only covers the case when you're running the JAR and natives get extracted into the Natives directory, but not when running using gradle and there's already a build/natives directory. The maven build is probably affected, too but I've never been successful in building using maven (it's probably my setup).

```
Sun Feb 11 18:53:02 EST 2018 ERROR:Cannot run program "/scratch/opsu/./build/natives/ffmpeg64": error=13, Permission denied
java.io.IOException: Cannot run program "/scratch/opsu/./build/natives/ffmpeg64": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at itdelatrisu.opsu.video.FFmpeg.extractMetadata(FFmpeg.java:97)
        at itdelatrisu.opsu.video.Video.<init>(Video.java:80)
        at itdelatrisu.opsu.states.Game.loadVideo(Game.java:1976)
        at itdelatrisu.opsu.states.Game.enter(Game.java:1654)
        at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:248)
        at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
        at itdelatrisu.opsu.Container.gameLoop(Container.java:136)
        at itdelatrisu.opsu.Container.start(Container.java:80)
        at itdelatrisu.opsu.Opsu.main(Opsu.java:213)
Caused by: java.io.IOException: error=13, Permission denied
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 9 more
```

**Comment by itdelatrisu** [comment]
Is this solved by changing `getNativeLocation()` in [FFmpeg.java](https://github.com/itdelatrisu/opsu/blob/master/src/itdelatrisu/opsu/video/FFmpeg.java#L69) to this?

```
private static File getNativeLocation() {
	File customLocation = Options.getFFmpegLocation();
	File f = (customLocation != null && customLocation.isFile()) ? customLocation : FFMPEG_PATH;
	if (!Files.isExecutable(f.toPath())) {
		f.setExecutable(true);
	}
	return f;
}
```

**Comment by tpenguinltg** [comment]
@itdelatrisu Yes, it appears so. I'm not so sure about stuffing it in that function as it would result in too many concerns, but I guess it's fine as long as you're okay with the side effect.

**Comment by itdelatrisu** [comment]
Committed in cd1cdf8, thanks!

**Pull request closed without merging**
