### PR TITLE
Add GStreamer player

### PR DESCRIPTION
**Pull request by DarkTigrus**
GStreamer based music player for opsu. [GStreamer](http://gstreamer.com/) is a pipeline-based multimedia framework.

Why GStreamer is awesome:
  * Really powerful and easy to use.
  * No more dynamic 50-150 offset. Perfect sync. Offset is 0 by default.
  * Plugins for everything. DoubleTime now sounds like DoubleTime.
  * Should work everywhere, even on android.

Currently tested on linux64, win32, win64. Requries gstreamer-java-1.6.jar for compiling and gstreamer-0.10 for launch.

Some concerns:
Size of libraries. ~12Mb (compressed) just for one Windows architecture. Most Linux distributions provides gstreamer package.  And i didn't touched Mac os.
I didn't managed to pack libraries into jar. x86 and x86_64 files conflicts. jna.library.path and java.library.path doing nothing. Also .jar/theme.ogg can't be played.
I don't know how to supplie [gstreamer-java 1.6](https://code.google.com/p/gstreamer-java/downloads/detail?name=gstreamer-java-1.6.jar) properly for better workflow. Maven version is outdated.

### CODE REVIEW

**Comment by itdelatrisu** [comment]
Sorry for the terribly late reply.  What do I need to be able to run this on Windows?

**Comment by LemonLake** [comment]
Looks like the GitHub version is not outdated:
https://github.com/gstreamer-java/gstreamer-java

Haven't checked the maven repo on this but it probably looks like we're
going to have to compile and distribute. What's the license for GStreamer?

**Comment by DarkTigrus** [comment]
Work still in progress. PR is pretty outdated. I have some nice progress with all issues i described in a first post. I'll try to push updated version in a few days.

You can build opsu-runnable.jar as usual If you want to try it right now. To run it though you need to download and unpack GStramer SDK 0.10 somewhere in the %PATH%. Next update will eliminate that step.

GStreamer-java have LGPL license. Google code's latest binary version is 1.6 which i ship into the local repository via maven plugin. Downside is that IDEs (at least Idea) would miss dependency without calling ```mvn validate``` at least once. Not sure what can be done about it.

**Comment by LemonLake** [comment]
Not really a problem, it's a generic step for maven dependencies in general.

**Comment by DarkTigrus** [comment]
A bit overestimated my free time due to exams. Finally got around to finish PR.

Notable changes:
  - ```NativeLoader``` extracts and loads native libraries from .jar depends on OS and architecture . With a bit modification it can fully replace JarSplice.
  - SlickPlayer still presents in opsu in case gstreamer not working on some machines. I may add switch in option menu to select music engine if it's needed.

Things that need to be done:
  - OS X libraries are missing. i don't have an Apple desktop to do it myself.
  - opsu always presented with offset -75 setting by default. Now, when music is perfectly in sync, it can be a problem. Any idea how to handle it?

**Comment by Bigpet** [comment]
I'm really confused about some weird glitches where the slider-ball stays at the end of some slider too long. Here's the video: https://www.youtube.com/watch?v=EqnAOVKhSSw (the two blue sliders at the beginning and a few green slider later). The song is https://osu.ppy.sh/s/14994 and for me it happens each time I play the song.

Also, I had an issue with the dll loader loading the wrong *.dlls with the same name from paths in my PATH directory. Probably not a big deal but it would be nice to not have that happen

**Comment by LemonLake** [comment]
Any update on this?

**Comment by DarkTigrus** [comment]
Still need help from someone with Mac to pick OS X dependency. And somehow get rid of offset -75 in all existing installations. Otherwise it's done. I rebased it to master to avoid confusion.

**Comment by abalabahaha** [comment]
I've got a MBP running OSX Yosemite. How can I help?

**Comment by iceblade112** [comment]
Oh.. RIP

**Comment by Lemmmy** [comment]
make opsu in c++ and use BASS


wait

**Pull request closed without merging**
