### PR TITLE
Added GL version to error handler

### PR DESCRIPTION
**Pull request by Lemmmy**

### CODE REVIEW

**Comment by itdelatrisu** [comment]
If there's no OpenGL context when this fires, you'll get a `RuntimeException` on that line:
```
java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glGetString(GL11.java:1792)
```

**Comment by Lemmmy** [comment]
Does that fix it?

**Comment by itdelatrisu** [comment]
Have you gotten this to work?  I don't think we can get the value in that class, since a lot of exceptions (esp. uncaught exceptions caught in `Thread.setDefaultUncaughtExceptionHandler()`) seem to run in a different thread (i.e. without the OpenGL context).

**Comment by itdelatrisu** [comment]
Done in af667a4. Thanks!

**Pull request closed without merging**
