### PR TITLE
Lower GLSL version requirement

### PR DESCRIPTION
**Pull request by Bigpet**
I didn't really use any of the newer features anyway.
This should accomodate open source drivers that use older versions of MESA.

Related to #120

### CODE REVIEW

**Comment by mad-s** [comment]
Please lower the OpenGL version requirement in src/itdelatrisu/opsu/objects/curves/Curve.java:90 to OpenGL 3.0 instead of OpenGL 3.3

**Comment by Bigpet** [comment]
@mad-s I guess that would work fine. Technically we would need to check if glsl version "130" is supported too. But I don't know of a driver that supports GL 3.0 but not GLSL 130

**Comment by mad-s** [comment]
According to https://en.wikipedia.org/wiki/OpenGL_Shading_Language#Versions OpenGL 3.3 corresponds to GLSL 3.3 and OpenGL 3.0 corresponds to GLSL 1.3. This is also the reason for 940e9baa41674d5a272bfad2a55f53a86d518b51, which fixed slider rendering for my GPU.

**Comment by Bigpet** [comment]
@mad-s well that means that GLSL 330 and GL 3.3 were released alongside. But if you read the OpenGL specification then you'll realize that those standards are still seperate and to get a conforming OpenGL 3.3 implementation you do not actually need to support GLSL 330. (If this were the case then #120 would be a bug in noveau, but it's not)

**Comment by itdelatrisu** [comment]
Thanks again for taking care of this.  Though, why aren't we checking if GLSL 130 is supported?

**Comment by Bigpet** [comment]
@itdelatrisu because I'm lazy :smile: . Also, there's no really good way to poll it other than writing a minimally viable shader program in that version and try to compile and link it. You can only query the highest supported version and I don't think an implementation has to support all previous versions.

**Pull request merged**
