### PR TITLE
Rewrote shaders for GLSL 110 (openGL2.0).

### PR DESCRIPTION
**Pull request by Szunti**
For poor guys with eg. old intel gma mobile gpus.

### CODE REVIEW

**Comment by itdelatrisu** [comment]
Just running a quick search through `itdelatrisu.opsu.render`, there are these `GL30` calls in `CurveRenderState.java`:
* `GL30.glBindFragDataLocation(program, 0, "out_colour");`
* `GL30.glGenerateMipmap(GL11.GL_TEXTURE_1D);`

**Comment by Szunti** [comment]
Does it look better now?

out_colour variable was deleted in the GLSL110 version, so I deleted the glBindFragDataLocation call.
GenerateMipmapEXT is part of the EXTFramebufferobject extension, so I changed to that version.

**Comment by Szunti** [comment]
Actually I did care about checking the GL2+ things except for GenerateMipmap, where I thought it's not a tragedy if that fails. 

The other line sneak in beacuse I edited the files before f0b87c99abc51d572085e6b6b36a9fd984dffa68 and rebased the commit.

**Comment by itdelatrisu** [comment]
Other than removing the unused `org.lwjgl.opengl.GL30` import, it looks fine to me, but I'll leave this open for a day or so in case anyone else has comments (since I still know nothing about OpenGL :P).  Thanks again!

**Pull request merged**
