### PR TITLE
Stacking algorythm fix

### PR DESCRIPTION
**Pull request by AndreySeVeN**

### CODE REVIEW

**Comment by Lemmmy** [comment]
why was this necessary...?

**Comment by AndreySeVeN** [comment]
I'm C++ coder

**Comment by tpenguinltg** [comment]
Doesn't compile. You're missing a `*`.
```
$ gradle jar
Starting a Gradle Daemon (subsequent builds will be faster)
:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
/scratch/opsu/src/itdelatrisu/opsu/states/Game.java:1846: error: ';' expected
                        return mid + (max - mid)(difficulty - 5.0f) / 5.0f;
                                                ^
/scratch/opsu/src/itdelatrisu/opsu/states/Game.java:1846: error: not a statement
                        return mid + (max - mid)(difficulty - 5.0f) / 5.0f;
                                                            ^
/scratch/opsu/src/itdelatrisu/opsu/states/Game.java:1846: error: ';' expected
                        return mid + (max - mid)(difficulty - 5.0f) / 5.0f;
                                                                  ^
/scratch/opsu/src/itdelatrisu/opsu/states/Game.java:1848: error: ';' expected
                        return mid - (mid - min)(5.0f - difficulty) / 5.0f;
                                                ^
/scratch/opsu/src/itdelatrisu/opsu/states/Game.java:1848: error: not a statement
                        return mid - (mid - min)(5.0f - difficulty) / 5.0f;
                                                        ^
/scratch/opsu/src/itdelatrisu/opsu/states/Game.java:1848: error: ';' expected
                        return mid - (mid - min)(5.0f - difficulty) / 5.0f;
                                                                  ^
6 errors
1 warning
:compileJava FAILED
```

**Comment by itdelatrisu** [comment]
Can someone describe what this is fixing? (linking: #183)

**Comment by itdelatrisu** [comment]
Fixed in 9b5f26d.

**Pull request closed without merging**
