### PR TITLE
Optionmenu navigation

### PR DESCRIPTION
**Pull request by yugecin**
Sidebar navigation for the option menu, as described in #283 

Some differences between this and osu!:
* The pink indicator fades in osu! when active group changes.
* This nav menu is scrollable in osu!. I tested on 800x600 and all items fit on screen so I didn't make it scrollable.

Notes:
* I made a mess in `MainMenu` & `SongMenu` for animations alpha. The option menu fades quicker than the navigation elements in the menu, so I had to adjust some things. It's now a bit messier as the fading animation is not handled in the `OptionsOverlay` class, but on other places.
* ~~I made some (shit) icons based on the ones in osu!, if anyone is experienced in making such images, _please_ make better ones ^^~~ Used font-awesome
* Section headers will be slightly transparant when they're not the active section on screen, like in osu!

Extra: Search filter won't accept new characters when there would be no results + added the little animation that osu! does when that happens.

_I didn't forget to commit the added resources for once, yey!_

~~**EDIT:** hold on, someone suggested to use font-awesome for the icons, I'll probably delete the commit with my shitty icons~~ done

### CODE REVIEW

**Comment by itdelatrisu** [comment]
This looks amazing, thanks so much!  Only a few comments:
* Options overlay should be a little wider (about 40% of the screen in osu!, 35% in opsu!).
* When options in multiple categories all fit on one page (ex. with a search filter), clicking anything but the top category causes a slight jitter; it should do nothing at all.

**Comment by tpenguinltg** [comment]
Nice work!

Like @itdelatrisu mentioned, I would suggest widening the overlay because the text in long lines get cut off (e.g. the option under Language) and short sliders like the "Track checkpoint" slider is also almost unusable.
screenshot_20170528_185010
screenshot_20170528_185615

**Comment by yugecin** [comment]
Done & done!

The width was a silly mistake; it was 0.42x the width but the width of the nav bar was subtracted from it... I fixed that and made it 0.4x width for widescreen, and 0.5x for 4:3 resolutions (as in osu!).

**Comment by itdelatrisu** [comment]
Thanks again! :)

**Pull request merged**
