### PR TITLE
Slider improvements (fade in ticks, fade out reversearrow, animations)

### PR DESCRIPTION
**Pull request by yugecin**
Fade out reverse arrow when passed repeat
Fade in sliderticks when passed repeat

### CODE REVIEW

**Comment by itdelatrisu** [comment]
Thanks again!  I'm a little hesitant on fading out the reverse arrows without implementing the full related behavior -- the hitcircle/hitcircleoverlay sprites also fade out when that point on the slider is done with.  Otherwise, this is kind of distracting on its own.

**Comment by yugecin** [comment]
Yep, will do

**Comment by itdelatrisu** [comment]
Yeah, that's right (I think).  From looking at osu! a few more times, this is what I can gather:
- The circles start fading out right after the time has passed (if it won't get hit again with repeats), even if you *weren't* holding the slider.
- If you *were* holding the slider, there should be a "pop" effect (fade+scale) for the hit circles.  This should be at every point on the slider (e.g. first point, any repeats, last point).  Note: currently, opsu! has a "pop" only at the end of a slider, and it's actually implemented wrong -- it currently pops if the **slider score** was not a miss, but it should really only consider if you were holding the slider **at that point**.
Thanks so much for helping out!

Off-topic: I just noticed your cursordance project, it's really cool! :)

**Comment by yugecin** [comment]
I recorded some gameplay and watched it frame by frame, these are my notes:
* holding slider
  * initial circle: pop
  * end circle: pop
  * return point: pop reverse arrow & pop circle
* not holding slider
  * initial circle: fade out
  * end circle: disappear
  * return point: reverse arrow disappears & circle disappears
* when a circle popped/faded/disappeared, fade in a new circle (and reversearrow if needed) if the ball has to return to this point again, seems like alpha is 1f at the first slidertick (should check with sliders without sliderticks)

--
Thanks :D I'll add it to opsu! too when I have the chance.

**Comment by yugecin** [comment]
Should be ready to go :)

**Comment by itdelatrisu** [comment]
This looks amazing! Thanks so much! 😄

About the sliders cutting off - we can wait for a reply (in #215), or you could make a temporary fix to always draw the end circle and we can revert it later.  What would you prefer?

**Pull request merged**
